version: '3.7'
services:
  cosuno-test-app:
    container_name: cosuno-test-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - ${APP_PORT}:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${API_HOST}:${API_PORT}

  cosuno-test-api:
    build: ./api
    container_name: cosuno-test-api
    ports:
      - '${API_PORT}:3000'
    environment:
      - API_URL=${API_HOST}:${API_PORT}
    volumes:
      - ./api:/usr/src/app
      - '/app/node_modules'